###
GET http://localhost:4000/homepage/1


###
POST http://localhost:4000/homepage
Content-Type: application/json

{
            "id": "",
			"orderNumber":"4",
            "internalOrderNumber": "",
            "creationDate": "",
            "name": "",
            "phoneNumber": "",
            "email": "",
			"sellerStore":"",
            "shippingMethod":"",				
			"shippingAddress": "",
            "shippingCity": "",
            "shippingRegion": "",
            "shippingCountry": "",
			 "pack_promise_min": "",
			 "pack_promise_max": "",
			 "ship_promise_min":"",
			 "ship_promise_max": "",
			 "delivery_promise_min": "",
			 "delivery_promise_max": "",
			 "ready_pickup_promise_min":"",
			 "ready_pickup_promise_max": "",
			 "lineItem":[
			{
			 "id": "",
			 "productName": "",
			 "productQty":"",
			 "productWeight": ""
			}
			]
			 
			

        }
    


